---
##################################
# Download and install terragrunt 
##################################

- name: "Download Terragrunt version {{ terragrunt_install_version }}"
  get_url:
    url: "{{ terragrunt_url }}"
    dest: "{{ terragrunt_download_location }}"
  when: current_terragrunt_version.rc != 0

- name: Move Terragrunt binarie for execution
  copy:
    remote_src: true
    src: "{{ terragrunt_download_location }}/{{ terragrunt_downloaded_file_name }}"
    dest: "{{ terragrunt_execution_path }}/{{ terragrunt_execution_file_name }}"
    mode: u+x,g+x,o+x
  when: current_terragrunt_version.rc != 0
  become: true
